/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kFontPkg = null;

  static const IconData corona = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recovered = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dead = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData active = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_chart = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData launch = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
